---
- hosts: all
  tasks:
    - name: Installing Updates 
      apt:
        force_apt_get: yes
        cache_valid_time: 3600
        force: yes
        update_cache: yes
        upgrade: 'dist'
      become: yes
    - name: Adding Universe Repository  
      shell: 'add-apt-repository universe -y'
      become: yes
    - name: Instalando ruby-dev    
      apt:
        name: ruby-dev
        state: latest
      become: yes
    - name: Installing libsqlite3-dev  
      apt:
        name: libsqlite3-dev
        state: latest
      become: yes
    - name: Installing libssl-dev  
      apt:
        name: libssl-dev
        state: latest
      become: yes
    - name: Installing pkg-config  
      apt:
        name: pkg-config
        state: latest
      become: yes
    - name: Installing cmake  
      apt:
        name: cmake
        state: latest
      become: yes
    - name: Installing libssh2-1-dev
      apt:
        name: libssh2-1-dev
        state: latest
      become: yes
    - name: Installing libicu-dev  
      apt:
        name: libicu-dev
        state: latest
      become: yes
    - name: Installing zlib1g-dev  
      apt:
        name: zlib1g-dev
        state: latest
      become: yes
    - name: Installing g++  
      apt:
        name: g++
        state: latest
      become: yes
    - name: Installing Oxidized - Web and Script  
      shell: 'gem install oxidized && gem install oxidized-script oxidized-web'
      become: yes
    - name: Creating oxidized directory  
      shell: 'oxidized || /bin/true'
      become: yes
    - name: Copying router.db to oxidized directory  
      shell: 'cp  /home/ptg/router.db /root/.config/oxidized/'
      become: yes
    - name: Copying config to oxidized directory   
      shell: 'cp /home/ptg/config /root/.config/oxidized/'
      become: yes


